### ISSUE TITLE
belief never updates message

### ISSUE THREAD

**Issue by danmackinlay** [gaussianBP/gaussianBP.github.io#3]
I think this is a purely notational problem. Or maybe it is a problem with my brain.

But examine the BP equations in https://gaussianbp.github.io/#the-belief-propagation-algorithm —
The formulae give update rules for the variable beliefs $b$ in terms of messages $m$ from adjacent nodes. That seems fine. However, there is no point at which beliefs $b$ influence messages $m$, which is rather at odds with the iterative setup of the model; once we have generated an updated belief $b$ at a given variable, shoudl we not wish to generate a new message from that node to propagate to the adjacent factors? 

<img width="497" alt="Screenshot 2023-06-23 at 9 31 28 am" src="https://github.com/gaussianBP/gaussianBP.github.io/assets/21740/93b91b67-ffa4-4b31-8ef6-4cf9b110f1fc">

But since no $m$ depends upon any $b$, there is no iteration to be done; so why does the algorithm seem to imply there is something to be done after updating beliefs?
<img width="747" alt="Screenshot 2023-06-23 at 9 33 05 am" src="https://github.com/gaussianBP/gaussianBP.github.io/assets/21740/accbae97-106e-47c2-84b0-8fd4420de7f6">

(this lack of updating the $b$ terms also seems to me to be a problem with the derivation https://gaussianbp.github.io/#derivation )

I think what we actually want to do (correct me if I'm wrong) is to allow the messages from variable nodes to include the node belief, as in the `compute_messages` method of [this implementaion](https://colab.research.google.com/drive/1-nrE95X4UC9FBLR0-cTnsIP_XhA_PZKW#scrollTo=tlWYSDnqxJUW&line=393&uniqifier=1).

Or am I confused?

**Comment by joeaortiz** [comment]
Hi Dan, that's a great question and something that is probably presented a bit ambiguously in this article. 

The second figure you pasted in that shows the 3 phases of GBP is slightly misleading because the belief update is never actually needed. Only var-to-fac and fac-to-var message passing is required for BP, and the beliefs (which are computed by multiplying incoming fac-to-var messages) are ephemeral properties of the graph that can be computed at any point in time to give an estimate of the marginals. In other words, GBP updates the messages in the graph and the beliefs (being a fn of the messages) are a property of the graph that can be computed at any point.

The reason we present 3 phases in the article is that all implementations of GBP (that I've seen), one does always compute the beliefs at each iteration after the fac-to-var MP phase. There are 2 main reasons for this: 1) it is useful to keep track of the marginal estimates for convergence checks etc, and 2) the var-to-fac messages can be replaced by just sending the current beliefs (the true var-to-fac are not equal to the beliefs but can be recovered at the factor by dividing by the most recent outgoing message - this is what you can see in lines 406-407 in [our implemenation](https://colab.research.google.com/drive/1-nrE95X4UC9FBLR0-cTnsIP_XhA_PZKW#scrollTo=tlWYSDnqxJUW&line=406&uniqifier=3) ).

Feel free to re-open this if you have any follow up questions/comments.

**Comment by joeaortiz** [comment]
I'll add a couple of sentences to the article to clarify the figure showing 3 phases and that the beliefs are ephemeral properties of the graph.
